/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package edu.gatech.chai.fhir.decedent_index.api;

import edu.gatech.chai.fhir.decedent_index.model.Decedents;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-01-23T23:26:47.338890-05:00[America/New_York]")
@Api(value = "search", description = "the search API")
public interface SearchApi {

    @ApiOperation(value = "searches indexes", nickname = "searchDecedent", notes = "By passing in the appropriate options, you can search for decedent indexes ", response = Decedents.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = Decedents.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/search",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Decedents> searchDecedent(@NotNull @ApiParam(value = "casd number at ME office", required = true) @Valid @RequestParam(value = "case-number", required = true) String caseNumber,@NotNull @ApiParam(value = "ME office name", required = true) @Valid @RequestParam(value = "medical-examiner-office", required = true) String medicalExaminerOffice,@ApiParam(value = "name of decedent") @Valid @RequestParam(value = "name", required = false) String name,@ApiParam(value = "search family name porition of name") @Valid @RequestParam(value = "family", required = false) String family,@ApiParam(value = "search given name portion of name") @Valid @RequestParam(value = "given", required = false) String given);

}
